### ISSUE TITLE
Changelog missing after 4.1.0

### ISSUE THREAD

**Issue by TZanke** [django-treebeard/django-treebeard#100]
http://django-treebeard.readthedocs.io/en/latest/changes.html

searching for django 1.11 support in changelog but newest releases are missing.

**Comment by jedie** [comment]
Think >4.2.0 will support django v1.11, see: https://github.com/django-treebeard/django-treebeard/issues/90

**Comment by ca-simone-chiorazzo** [comment]
Just to keep this issue updated, the problem is still there. We are now at v4.3.1 but the changelog of https://django-treebeard.readthedocs.io/en/latest/changes.html is frozen to v4.1.0 .

**Comment by tabo** [comment]
We have https://github.com/django-treebeard/django-treebeard/blob/master/CHANGES.md up to date but yes, something is wrong with the docs generator

**Comment by tabo** [comment]
Filed #204

**Comment by solarissmoke** [comment]
Fixed in #204.
