### ISSUE TITLE
database could not be created

### ISSUE THREAD

**Issue by TZanke** [django-treebeard/django-treebeard#101]
After setting up the system and running all migrations treebeard wants to create a database. But we don't allow the system to create databases by itself. Also I cannot find any package in our pypi repo which creates a database with py.test. `create_test_db` looks like the method django test uses to create the database at beginning of tests. Why does treebeard create the database again?

Source:
https://github.com/django-treebeard/django-treebeard/blob/24126188e0a346f32269f250282e79f711fa2031/treebeard/tests/conftest.py#L30

**Comment by jrief** [comment]
does it try to create the database during normal operation, ie. outside of a unit testing run?

**Comment by tabo** [comment]
This can be solved by using a "new" option in Django 1.8: `keepdb`: https://docs.djangoproject.com/en/3.1/topics/testing/advanced/#django.db.connection.creation.create_test_db

**Comment by solarissmoke** [comment]
Fixed in #206.
