### ISSUE TITLE
How to add child for Harddrives in given Documentation

### ISSUE THREAD

**Issue by ekateam** [django-treebeard/django-treebeard#114]
[(http://django-treebeard.readthedocs.io/en/latest/tutorial.html)]
like adding desktop memory to memory ` `get(node.pk).add_child(name='Desktop` Memory')`.

**Comment by jrief** [comment]
please be more specific

**Comment by jrief** [comment]
Please ask on https://stackoverflow.com/questions/tagged/django-treebeard
