### ISSUE TITLE
Widget to pick ForeignKey to a treebeard model

### ISSUE THREAD

**Issue by guettli** [django-treebeard/django-treebeard#120]
My models has a ForeignKey to a model using treebeard.

I would like to render a user interface to make it easy to select an item from the tree.

Can you give me (or all users in the docs) an advice how to proceed?

I once have seen that the JS library select2 has an tree add-on.

Autocomplete would be great.

Here is a screen shot of what my dream looks like 

![grafik](https://user-images.githubusercontent.com/414336/44572022-da9b5480-a782-11e8-8c34-0568811738ae.png)

Maybe I am blind, and there is already something like this.

Source of the image: https://github.com/clivezhg/select2-to-tree

**Comment by guettli** [comment]
Hello, is anybody out there? What do you think about this feature request?

**Comment by jrief** [comment]
Since select2-to-tree supports a kind a Ajax-request, this certainly could be implemented. Either as a third party app, or as an Django-Admin addon to django-treebeard.

Feel free to implement it yourself or ask me for paid support using my private email address.

**Comment by tombreit** [comment]
Perhaps something like https://github.com/netzkolchose/django-treewidget ?

**Comment by tabo** [comment]
Well `django-treewidget` is pretty fantastic!
