### ISSUE TITLE
Add MP_Node to existing model

### ISSUE THREAD

**Issue by thiras** [django-treebeard/django-treebeard#125]
I'm trying change one of my models to MP_Node. When I try to makemigrations, it asks one-time `depth` and `path` values. I've couldn't find those default values in the documentation. What should be the default values of those?

Also it might good idea to add instructions about that to documentation.

**Comment by jrief** [comment]
NS_Node and MP_Node have completely different structures. If you want to migrate one into another, create a second model inheriting from MP_Node, then traverse the source tree, and for each node create a corresponding copy in your destination tree. After that remove the source tree, and rename the destination to the old name.

**Comment by helderco** [comment]
The OP didn't specifically say the existing model is an NS_Node. In my case, I'm trying to add hierarchy to a normal django model. 

I can understand right away that depth should be 2, and I should create a RunPython migration operation to add the root and update all the other parents to this.

But what about path? And is there any command that has to be run afterward to insure integrity?

**Comment by helderco** [comment]
Here's how I did my migration. I wanted all existing nodes to be root nodes.

```python
from django.db import migrations, models
from treebeard.mp_tree import MP_Node

# update if needed
steplen = MP_Node.steplen
alphabet = MP_Node.alphabet
node_order_by = ["name"]


def update_paths(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    nodes = Node.objects.all().order_by(*node_order_by)
    for i, node in enumerate(nodes, 1):
        # for default values, this resolves to: "{:04d}".format(i)
        node.path = f"{{:{alphabet[0]}{steplen}d}}".format(i)
    if nodes:
        Node.objects.bulk_update(nodes, ["path"])


def backwards(apps, schema_editor):
    """nothing to do"""


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="node",
            name="depth",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="node",
            name="path",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.RunPython(update_paths, backwards),
        migrations.AlterField(
            model_name="node",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
```

Notice how I remove the unique validation when adding the path field because of existing rows. After updating paths, it's added again.

As for numchild, it already has the right default and for depth I give a value of 1 (root), only in the migration (`preserve_default=False`).

**Comment by buczek** [comment]
> `node.path = f"{{:{alphabet[0]}{steplen}d}}".format(i)`

Doesn't use the alphabet at all, just the first character?  `'{:04d}'.format(i)` produces legal paths , but only if alphabet happens to start with "0".

Alternative (coded here for a "Group" model, not for a "Node" model):
```
from treebeard.mp_tree import MP_Node

def update_path(apps, schema_editor):

    class Node(MP_Node):
        # may overwrite, should match new model:
        # steplen = 4
        # alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        # node_order_by = []
        pass;

    Group = apps.get_model("personal","Group")
    db_alias = schema_editor.connection.alias

    for i, group in enumerate(Group.objects.all(), 1):
        group.path = Node._get_path(None, 1, i)
        group.save(using=db_alias)

**Comment by tabo** [comment]
Sorry I am late to the party, but I specifically wrote [`dump_bulk()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.dump_bulk) and [`load_bulk()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.load_bulk) for this particular use case.

**Comment by mpasternak** [comment]
I'm trying to make an existing model a MP_Node and I'm planning to use this migration. Is this approach anywhere in the docs?

**Comment by bmihelac** [comment]
This article provides a step-by-step guide on how to migrate an existing model with data while preserving its structure using Django migrations: https://code.informatikamihelac.com/en/django-treebeard-converting-an-existing-model-to-mp_node/
