### ISSUE TITLE
Custom queryset 'as_manager' failing

### ISSUE THREAD

**Issue by Guilouf** [django-treebeard/django-treebeard#135]
I wanted to use a custom queryset, to to filter queries, like retrieve only the root nodes from a queryset.
As stepped in the docs, i sublclassed  the `MP_NodeQuerySet` base queryset.
So there is `models.py`:

```python
class FooQueryset(MP_NodeQuerySet):
    def all_roots(self):
        """Select only root nodes"""
        return self.filter(depth=1)


class Foo(MP_Node):
    comment = models.CharField(max_length=20)
    objects = FooQueryset.as_manager()
```

When i want to populate the database,

```python
        roots_ao = [
                {'data': {'comment': "rag", }, },
                {'data': {'comment': "nia", }, },
                {'data': {'comment': "niaaa", }, }]

        Foo.load_bulk(roots_ao)
```
It fails with the third entry: 
```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "foo_path_key"
DETAIL:  Key (path)=(0002) already exists.
```

If i only want to create 2 objets it's ok. I guess the problem is that i use the `as_manager()` method, and that case was not taken into account.

**Comment by tabo** [comment]
You need to create another separate queryset. Treebeard relies on a functional `objects` default queryset.

**Comment by mathiasose** [comment]
For anyone coming in here from a search like I did, I think I have found a way that seems to work:

1. Make your custom `QuerySet` inherit from `MP_NodeQuerySet`
```python
class TopicQuerySet(MP_NodeQuerySet):
    ...

    def root_nodes(self) -> 'TopicQuerySet':
        return self.filter(depth=1)
```

2. Make a custom `Manager` using `MP_NodeManager.from_queryset` and reimplement `get_queryset`. This way you get everything from your custom queryset to combine with the `get_queryset` method of the manager that sets `order_by`.
```python3
class TopicManager(MP_NodeManager.from_queryset(TopicQuerySet)):
    """Custom manager for nodes in a Materialized Path tree."""

    def get_queryset(self):
        """Sets the custom queryset as the default."""
        return self._queryset_class(self.model).order_by('path')
```

3. Use the custom manager class in your model::
```python3
class Topic(MP_Node):
    ...

    objects = TopicManager()
```
