### ISSUE TITLE
When is the new release?

### ISSUE THREAD

**Issue by VyasPragati** [django-treebeard/django-treebeard#139]
We are using django-treebeard in our project, recently we see an issue similar to https://github.com/django-treebeard/django-treebeard/issues/65 . 

I saw there was some fix committed on Jun 21, 2018 in the master branch which hasn't been released lately:https://github.com/django-treebeard/django-treebeard/pull/112

Also recently new Django version > 2.0 have been released will there be a future support or releases for django-treebeard please let me know?

Thanks

**Comment by rvanlaar** [comment]
I made a release from the latest git today: django-treebeard-rvanlaar

**Comment by jrief** [comment]
@VyasPragati @rvanlaar I just retried to release a new version. For some unexplainable reasons, I'm unable to build django-treebeard on Travis-CI. Does anybody have an idea?
Details here: https://travis-ci.org/django-treebeard/django-treebeard/builds/629353039

**Comment by rvanlaar** [comment]
Isn't rhebpostgres port normally 5432?

On 25 December 2019 12:31:44 CET, Jacob Rief <notifications@github.com> wrote:
>@VyasPragati @rvanlaar I just retried to release a new version. For
>some unexplainable reasons, I'm unable to build django-treebeard on
>Travis-CI. Does anybody have an idea?
>Details here:
>https://travis-ci.org/django-treebeard/django-treebeard/builds/629353039
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/django-treebeard/django-treebeard/issues/139#issuecomment-568889217

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jrief** [comment]
@rvanlaar I followed [these instructions](https://docs.travis-ci.com/user/database-setup/#postgresql), apparently without luck.

Btw. On other projects, I have so many issues with Travis-CI that I consider to move away from it. These many obscure errors are a huge waste of time for me. Do you have any experience with alternatives, such as CircleCI or so?

**Comment by rvanlaar** [comment]
@jrief I understand your reluctance in using Travis. My customers are all on bitbucket with bitbucket-pipelines. Which has it's own quirks. 

I looked at the travis documentation.
The only difference I could find was that the treebeard .yml file has single quotes around `10`. 
The documentation has double quotes.

It seems there is a solution for travis:
**https://travis-ci.community/t/postgresql-11-2-cannot-connect/2680/5**

It's also possible to file a ticket:
https://github.com/travis-ci/travis-ci/issues

**Comment by jrief** [comment]
that seems to be a solution.
