### ISSUE TITLE
error with self.node.get_last_child()._inc_path()

### ISSUE THREAD

**Issue by m-pasha** [django-treebeard/django-treebeard#140]
I get error with this line code
_treebeard/mp_tree.py:387_
`newobj.path = self.node.get_last_child()._inc_path()`

**`'NoneType' object has no attribute '_inc_path'`**

self have parent object page and in kwargs is instance.

`backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1  |     response = get_response(request)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend_1  |     response = self.process_exception_by_middleware(e, request)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
backend_1  |     response = viewfunc(request, *args, **kw)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
backend_1  |     return view_func(request, *args, **kwargs)
backend_1  |   File "/opt/project/pv/apps/wagtailoverrides/views/pages.py", line 246, in create
backend_1  |     parent_page.add_child(instance=page)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 1013, in add_child
backend_1  |     return MP_AddChildHandler(self, **kwargs).process()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 387, in process
backend_1  |     newobj.path = self.node.get_last_child()._inc_path()
backend_1  | AttributeError: 'NoneType' object has no attribute '_inc_path'
backend_1  | [21/May/2019 09:03:28] "POST /admin/pages/new/article/articlepage/5/ HTTP/1.1" 500 110440`

tech info:
python 3.6
Django 2.2.1
wagtail 2.5.1
django-treebeard 4.3
<img width="661" alt="image" src="https://user-images.githubusercontent.com/18262789/58092959-ab106000-7bcd-11e9-9089-d7f228fe8131.png">

**Comment by pinksharpii** [comment]
Did you figure out what the issue was? I'm having the same issue. Updating to 3.4.1 did not help.

**Comment by graingert** [comment]
![image](https://user-images.githubusercontent.com/413772/135589525-7f55bd41-7531-49a8-a631-a9f943e21b56.png)

**Comment by graingert** [comment]
https://github.com/django-treebeard/django-treebeard/issues/220 related?

**Comment by hazho** [comment]
I think I'll solve this one today
