### ISSUE TITLE
`load_bulk`, not `load_data`

### ISSUE THREAD

**Issue by gh640** [django-treebeard/django-treebeard#142]
`load_data()` in the following code snippet in the document should be `load_bulk()`, I believe.

```python
# parent = None
MyNodeModel.load_data(data, None)
```

- https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.load_bulk

(I searched for `load_data()` in the latest codebase and couldn't find.)

**Comment by rvanlaar** [comment]
This was fixed with: https://github.com/django-treebeard/django-treebeard/commit/8042ee939cb45394909237da447f8925e3cc6aa3

This issue can be closed when a new release and an update to the docs is done.

**Comment by tabo** [comment]
Thanks for the fix. I failed [a separate ticket](#204) to track the broken pipeline to update documentation.
