### ISSUE TITLE
Allow extending delete methods

### ISSUE THREAD

**Issue by virtosubogdan** [django-treebeard/django-treebeard#146]
**Issue**
Trying to extend the delete operation is not possible without patching. 
Because single node delete operations must turn into queryset deletes, certain overrides will be prevented.

This is an example:
```python
class SafetyQueryset(models.query.QuerySet):
    def delete(self, force_delete=False):
        for obj in self.all():
            obj.delete(force_delete=force_delete)


class SafetyManager(MP_NodeManager):
    _queryset_class = SafetyQueryset

    def get_queryset(self):
        return self._queryset_class(self.model, using=self._db)


class SafetyMixin(models.Model):
    objects = SafetyManager()

    class Meta:
        abstract = True

    def delete(self, force_delete=False):
        if force_delete:
            super(SafetyMixin, self).delete()


class SafeMP_TestNode(SafetyMixin, MP_Node):
    pass

SafeMP_TestNode.add_root().delete(force_delete=True) # will not delete
SafeMP_TestNode.objects.all().delete(force_delete=True) # will not delete
```
This is longer than needed but hopefully it illustrates the problem better.

My original issue was the same as https://github.com/django-treebeard/django-treebeard/issues/109, but I tried to turn into a general delete problem, that would be more fitted for testing inside django-treebeard.

**Proposal**
This code should be valid as per https://django-treebeard.readthedocs.io/en/latest/caveats.html, but I understand that it refers to an edge case.

Passing `*args, **kwargs` would not fix this use case.
A possible option is to add any hook to make treebeard use the original manager for deletes.
I'll open a pull request with tests and proposal fix, but I'm open to implementing this any other way.

**Comment by jrief** [comment]
> Because single node delete operations must turn into queryset deletes, certain overrides will be prevented.

what do you mean with *certain overrides*?

**Comment by virtosubogdan** [comment]
I meant to say that this `force_delete` override, while useful, is a bit weird.
A logging or an "also do this override" would not have this issue.

**Comment by tabo** [comment]
@virtosubogdan Hi. I think your problem is that you are not subclassing the MP_NodeQuerySet as recommended in the [warnings of MP trees](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node). That should solve your issues with deletion. Please reopen the ticket if the problem persists.
