### ISSUE TITLE
Dirty path max_length example redefinition in docs

### ISSUE THREAD

**Issue by bitphage** [django-treebeard/django-treebeard#149]
Docs [says](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node.path) to redefine path max_length you need to use ugly call `MyNodeModel._meta.get_field('path').max_length = 1024`

This is not true as MP_Node model is abstract model, thus allow to simply redefine fields like this:

`path = models.CharField(max_length=1024, unique=True)`

See
* https://docs.djangoproject.com/en/2.2/topics/db/models/#abstract-base-classes
* https://stackoverflow.com/questions/2344751/in-django-model-inheritance-does-it-allow-you-to-override-a-parent-models-a

**Comment by tabo** [comment]
@bitphage Thanks for reporting this issue. That recommendation was written for a very old version of Django. I'll update the docs once I can confirm this is no longer necessary.
