### ISSUE TITLE
Current static asset URL generation doesn't account for cloud storage

### ISSUE THREAD

**Issue by ahackit** [django-treebeard/django-treebeard#151]
The current get_static_url function doesn't account for cases where static assets are stored in cloud environments. Static asset URLs get directed to base domain.

Django provides a robust "static" template tag which generates needed URLs that point to your default static asset location.

I've created a PR for this here: https://github.com/django-treebeard/django-treebeard/pull/150

**Comment by solarissmoke** [comment]
Fixed in #150.
