### ISSUE TITLE
What is the maximum number of root nodes for the MP_Node?

### ISSUE THREAD

**Issue by ssrebelious** [django-treebeard/django-treebeard#154]
I have a model that might benefit from using of a tree-structure. However most of the records are supposed to be root nodes and only some of the records will be children. The table is supposed to be frequently updated, constantly adding new root nodes. It is expected to have over 10 000 000 of new root-nodes per month. How many root-nodes, that will be able to have children migt be stored using MP_Node? Should other structures be considered more viable in this case?

**Comment by seanucd2000** [comment]
It's a function of step length and the alphabet settings.  With postgres you can use a-z A-Z and 0-9, or 62 total different char combinations.  The default steplen of 4 is then 62^4, or roughly 14.8M root nodes.   A step len of 5 is 62 to the power of 5, or 916M.  And so forth....

The path field length divided by the step length will give you the total depth in children/descendants you can have.   So, the default path length of 255 and a step length of 4 will give you a max depth of 63 (have to round down, 256 would give you 64).

With that said, 10M root nodes (or individual trees) sounds insane to try to manage.  If the trees are shallow and don't move much, can you just add a foreign key to self on your model?  May be much more reliable and easier if you aren't shifting nodes around much or at all.  Good luck!

**Comment by ssrebelious** [comment]
Thanks for the clarification! I think it would be better indeed to switch to FK to self.
