### ISSUE TITLE
raise 'Failed lookup for key [depth]' error in Django 2.2

### ISSUE THREAD

**Issue by Yebing2018** [django-treebeard/django-treebeard#159]
Hi, In Debug mode, when I open the change_list page of a model that contains NS_Node or NP_Node, Django 2.2 raise ' django.template.base.VariableDoesNotExist: Failed lookup for key [depth] in '<td class="action-checkbox"><input type="checkbox" name="_selected_action" value="1" class="action-select"></td>' error
![image](https://user-images.githubusercontent.com/43950313/78127231-5d4bc180-7446-11ea-9a36-e15547a58a3a.jpg)

**Comment by tabo** [comment]
@Yebing2018 Could you please provide more information? Some sample code se we can reproduce the issue?

**Comment by solarissmoke** [comment]
I'm not able to reproduce this in Django 3.2 and master of treebeard. If it's still an issue, please reopen and provide a sample project/code that can be used to reproduce the problem.

**Comment by Yebing2018** [comment]
您好，您的邮件我已收到。谢谢！我现在不方便回复邮件内容，等有时间我会及时给您回复的！
