### ISSUE TITLE
MPNodeQuerySet.delete method does not have 'queryset_only' attribute set

### ISSUE THREAD

**Issue by nimasmi** [django-treebeard/django-treebeard#160]
Django's `QuerySet.delete` method has the attribute `queryset_only = True` [(source)][1]. This means that when `Manager.from_queryset(SomeQuerySet)` is used, the `delete()` method is not copied as a manager method[(source)][2].

Django documents this behaviour as a sort of safety feature: https://docs.djangoproject.com/en/3.0/topics/db/queries/#deleting-objects

Treebeard's MPNodeQuerySet does not have this attribute set. This means that calling `Manager.from_queryset(MPNodeQuerySet)` the resulting manager gets a `.delete()` method.

This is written from the perspective of the Wagtail project, whose `PageQuerySet` inherits from `MPNodeQuerySet`. In Wagtail it is possible to call `Page.objects.delete()`, whereas for any vanilla Django models, even within a Wagtail project, the response would be get:

```
>>> MyModel.objects.delete()
*** AttributeError: 'Manager' object has no attribute 'delete'
```

[1]: https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/db/models/query.py#L667
[2]: https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/db/models/manager.py#L92

I consider this a bug, because it deviates from the Django documentation, and is not itself documented.

Possible resolutions:

- decide it's not a bug
- document it
- add `.queryset_only` attribute to the `MPNodeQuerySet.delete` method

I have opened the related Wagtail issue https://github.com/wagtail/wagtail/issues/5937

**Comment by tabo** [comment]
Thanks for reporting this. There are many corners of treebeard that are still trying to support versions of Django from the time dinosaurs roamed the Earth. This feature was added to Django "only" 8 years ago.

That being said, deleting rows in treebeard isn't a trivial operation. During the design of the library, I tried to support all the Djangoisms I could, but safety always trumped that. I had to make many hard decisions regarding `delete()` years ago, so I'll have to catch up with current Djangoisms to see if we can support this "new" feature, or just document the difference so it doesn't catch users by surprise.

**Comment by nimasmi** [comment]
Thanks for replying.

Note that it's not the behaviour of `delete()` that would need to be changed, just the path of it within Python, when presented to other applications.

Currently the delete method is available at:

```python
MyModel.objects.delete()
MyModel.objects.all().delete()
MyModel.objects.any_other_queryset_generating_method().delete()
```

I'm suggesting removing the first of those, by the addition of the `.queryset_only` attribute, as suggested above.

I have tried the change locally, and existing tests are not broken, but admittedly the tests are complex enough that I wasn't sure how to add a failing test first.

PS A straw-man red herring: I started using Django in early 2011, and I'm pretty sure that the `delete()` method was protected on the manager then. I used the Django Book tutorial at the time: https://django-book.readthedocs.io/en/latest/chapter05.html#deleting-objects, though that seems to be from a 2012 commit. You may be right. 🤷
