### ISSUE TITLE
Multiple independent trees in a model

### ISSUE THREAD

**Issue by jphilip** [django-treebeard/django-treebeard#163]
Thank you for making this app available.
I am trying to port an existing nested set table which has one tree per account (multiple roots) and I want each account to be able to manage its own tree independently. The table has an account_id field.
Overriding the get_queryset method in the admin works to some extent, but not all. The logical thing would be to override the get_tree method of the model, but it is static and would need an extra parameter to load only the tree for the current account.
Is there a workaround, or would that be a new feature?
See: [https://stackoverflow.com/questions/61533257/porting-and-existing-nested-set-hierarchy](url)

**Comment by tabo** [comment]
@jphilip django-treebeard has supported multiple roots (trees) for more than a decade. You can add new roots by calling the `add_root()` method.
