### ISSUE TITLE
CI failing on master since 2019-01-23

### ISSUE THREAD

**Issue by hartwork** [django-treebeard/django-treebeard#167]
Hi!

From a quick look it seems that CI has been failing for Git master since 2019-01-23, currently both Travis and AppVeyor, see https://github.com/django-treebeard/django-treebeard/commits/master . Is anyone working on fixing the CI?

Best, Sebastian

**Comment by jrief** [comment]
Working on this issue would be really appreciated.

**Comment by hartwork** [comment]
I have pull request #168 ready for review now.
