### ISSUE TITLE
Publish releases as wheels?

### ISSUE THREAD

**Issue by thibaudcolas** [django-treebeard/django-treebeard#169]
I see on PyPI that the package’s releases only contain source distribution, for example for the latest [4.3.1](https://pypi.org/project/django-treebeard/4.3.1/#files). Would it be possible to additionally publish wheels?

The project is already set up for universal wheels since #130, and will switch to Python3-only wheels once #153 is merged – so I think this should just be a matter of adding `bdist_wheel` to the release process as described here: https://github.com/django-treebeard/django-treebeard/blob/3a8062cf4584336cc63551f332e9926e1af207ed/treebeard/__init__.py#L14

More general info on wheels: https://pythonwheels.com/. For me I’m particularly interested in speeding up installations.

**Comment by vsalvino** [comment]
I came here to ask the exact same question! Glad to see a PR is already in the works. I would be happy to pitch in if any extra hands are required to help get this released.

**Comment by thibaudcolas** [comment]
@jrief I see you closed this an hour ago and v4.4 was published then as well, but PyPI doesn’t have wheels for that release: https://pypi.org/project/django-treebeard/4.4/#files.

Wheels can still be added after the fact so this can still be fixed, but it’s preferable to always upload all distributions at the same time as there are a lot of installation tools that rely on storing the checksum of _all_ of a version’s distributions in order to provide reproducible installations.

**Comment by thibaudcolas** [comment]
I see v4.4 is now published as a wheel – thank you!
