### ISSUE TITLE
is_ancestor_of function feature request.

### ISSUE THREAD

**Issue by dstrohl** [django-treebeard/django-treebeard#188]
requesting a function "is_ancestor_of(node)".  There is already one for "is_sibling_of" and "is_decendant_of".

**Comment by tabo** [comment]
@dstrohl if you need `node1.is_ancestor_of(node2)`, right now you can just use `node2.is_descendant_of(node1)`.

see:
https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.is_descendant_of

you may also find useful:

https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_ancestors
