### ISSUE TITLE
Reconsider the testing matrix

### ISSUE THREAD

**Issue by tabo** [django-treebeard/django-treebeard#200]
Treebeard has a very comprehensive test suite and has a very extensive testing matrix. As of right now, tox is testing 4 versions of Python, 3 versions of Django, and 4 database backends.

The matrix started many, many years ago when Django was a young framework that [changed frequently and aggressively](https://code.djangoproject.com/wiki/RemovingTheMagic), and since we make use of very optimized raw sql in the library, we had to make sure it worked across DBMSs. When Django added Python 3 support, we added another dimension to the matrix and it has been like this for more than 10 years.

Do we need this testing rigor in 2021? Python seems to be much more conservative these days. What about Django? I would imagine they are very careful now being a established and mature framework. Running the whole test suite in tox takes me around 5 minutes, and I see it takes travis and appveyor around 15 minutes per commit. Are Python and/or Django changing in a pace that merits this testing?

**Comment by johanneswilm** [comment]
I agree on Python testing. 2 versions should be enough - For example the latest and the oldest hat is supported. Django does still change. I need to update my apps with every new version.

**Comment by tabo** [comment]
I was mistaken about travis' run time. It actually takes around an hour: https://travis-ci.org/github/django-treebeard/django-treebeard/builds/755017104

**Comment by solarissmoke** [comment]
The Travis run time is because they have been deliberately throttling builds on open source projects. We switched django-oscar to Github Actions and the same test matrix that took over 2 hours on Travis now runs in ~5 minutes. This isn't to say that the current matrix is necessary - just that the build time can be slashed regardless.

**Comment by solarissmoke** [comment]
The current matrix on Github actions takes less than 3 minutes in total, so I think this is a non-issue now.
