### ISSUE TITLE
The documentation is not being updated

### ISSUE THREAD

**Issue by tabo** [django-treebeard/django-treebeard#204]
The docs in https://django-treebeard.readthedocs.io/ are stale and not being updated by automation.

**Comment by tabo** [comment]
@jrief Could you please give me access to readthedocs? The documentation build has been broken for years: https://readthedocs.org/projects/django-treebeard/builds/

**Comment by jrief** [comment]
@tabo OK. I will check this. Today I wanted to build and release version 4.5, but had no time to update the ChangeLog. Will try next weekend.

**Comment by tabo** [comment]
Got the docs building again:

https://django-treebeard.readthedocs.io/en/latest/index.html
https://django-treebeard.readthedocs.io/en/stable/index.html
