### ISSUE TITLE
Move automation to Github Actions

### ISSUE THREAD

**Issue by tabo** [django-treebeard/django-treebeard#205]
Travis has [recently changed their pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). In the new free tier, they give 10,000 credits, at a rate of 10 credits per minute of linux node usage. This means 1,000 free minutes per month, which sounds like a lot, but when we're [using around 84 minutes of testing per commit](#200), this gives us 12 test runs in a month before we use our allotment.

Even if Travis decided to keep a free tier (doesn't seem like they will), they are limited to 5 concurrent jobs, while GH actions has 20 concurrent jobs in their free tier. This is big for us because currently we're using 48 jobs per commit (see #200).

The built-in secret store would allow us to integrate the workflow to publish docs and release to pypi from actions itself.

**Comment by johanneswilm** [comment]
Travis still does have an open source version - but their definition of open source has changed dramatically. Now it means anything without any corporate sponsorship whatsoever. If anyone contributing to the project receives any payment whatsoever, then it's no longer OSS according to travis. Converting to Github Actions takes a little effort, but overall they are very similar.
