### ISSUE TITLE
Revamp testing configuration

### ISSUE THREAD

**Issue by tabo** [django-treebeard/django-treebeard#206]
The tests in treebeard are very comprehensive, but the tooling and setup around them are from more than 10 years ago. Python, Django and Pytest have made a lot of progress that make many customizations in treebeard obsolete. These customizations may surprise possible contributors, so the testing should get up to date to modern standards.

**Comment by tabo** [comment]
Started some cleanup in [a branch](/django-treebeard/django-treebeard/tree/206-revamp-testing). Due to now relying on pytest-django, instead of our old locally sourced organically grown implementation, a test run is a bit slower, so I need to adjust the test helpers for the change. Everything is passing locally so we have that going.

**Comment by tabo** [comment]
Travis run was 2 times slower. Appveyor run was 3 times slower.

**Comment by johanneswilm** [comment]
@tabo Github is much faster than travis.

**Comment by tabo** [comment]
Merged #208
