### ISSUE TITLE
release

### ISSUE THREAD

**Issue by johanneswilm** [django-treebeard/django-treebeard#207]
Hey @tabo and @jrief ,
Could we get the current code released as a version? I see that @tabo opened a number of new tickets and a lot of that looks like it really would improve things a bit. But it also looked like it may take a while before anyone has time to look at those issues, right?

**Comment by jrief** [comment]
@johanneswilm since we add a new feature, would version 4.5 be OK for you?

**Comment by johanneswilm** [comment]
Yes, I think 4.5 sounds good.

**Comment by tabo** [comment]
@jrief While we're working on this, could you please take a look at #204 so that the docs are updated?

**Comment by johanneswilm** [comment]
Hey @tabo @jrief . I didn't quite get - do you need me to do something in order to get a release out the door?

**Comment by jrief** [comment]
if you can provide entries for 4.5 in the changelog, would be great. Thanks!

**Comment by johanneswilm** [comment]
@jrief OK, after scanning through the changelog, this is what I came up with: https://github.com/django-treebeard/django-treebeard/compare/master...johanneswilm:patch-1 Feel free to amen as necessary.

**Comment by jrief** [comment]
Thanks for providing the ChangeLog.
Just released 4.5. Hope everything is OK.

**Comment by tabo** [comment]
Thanks @johanneswilm @jrief 

@jrief Could you please give me access to RTD so I can fix the docs? They are not being updated.

**Comment by jrief** [comment]
@tabo just added `tabo` as maintainer to RTD. Sorry for locking you out, this was not intentional.

**Comment by tabo** [comment]
@jrief No worries! Thanks for setting RTD up! Docs used to live on my website, because RTD didn't exist back then, but it  is a much better solution now :)
