### ISSUE TITLE
Breaking changes introduced in django-treebeard 4.5

### ISSUE THREAD

**Issue by Aiky30** [django-treebeard/django-treebeard#210]
We have experienced breakages in django-cms due to the changes introduced in django-treebeard 4.5, the following change appears to have caused pain: https://github.com/django-treebeard/django-treebeard/pull/192/

## Some details of the issue and usage:

The usage in django-cms is a model that is being copied (not yet saved) and the _state.created is False. I'm not sure if this is misuse from the CMS or an oversight in django-treebeard.

The following code creates a copy of a model and then later tries to add a root node:
```
        if plugin_model != CMSPlugin:
            new_plugin = deepcopy(source_plugin)
            new_plugin.pk = None
            new_plugin.id = None
            new_plugin.language = language or new_plugin.language
            new_plugin.placeholder = placeholder
            new_plugin.parent = parent
            new_plugin.numchild = 0
        
        ...
        
        if parent:
            new_plugin = parent.add_child(instance=new_plugin)
        else:
            new_plugin = CMSPlugin.add_root(instance=new_plugin)
```
https://github.com/django-cms/django-cms/blob/0e557768af9208f54bea5abe5bb7e629bae2ab88/cms/utils/plugins.py#L194

This does appear to follow guidelines from Django regarding copying a model: https://docs.djangoproject.com/en/3.2/topics/db/queries/#copying-model-instances

I suspect the deepcopy exists to ensure that all of the plugin children are carried along too, a fundamental feature for the cms: https://www.programiz.com/python-programming/shallow-deep-copy

## Failing test, one of many:
```
ERROR: test_create_page_type (cms.tests.test_admin.AdminFormsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aiky30/Projects/aiky30-github/django-cms/cms/tests/test_admin.py", line 980, in test_create_page_type
    page.publish('en')
  File "/Users/aiky30/Projects/aiky30-github/django-cms/cms/models/pagemodel.py", line 982, in publish
    self._copy_contents(public_page, language)
  File "/Users/aiky30/Projects/aiky30-github/django-cms/cms/models/pagemodel.py", line 628, in _copy_contents
    placeholder.copy_plugins(target_placeholder, language=language)
  File "/Users/aiky30/Projects/aiky30-github/django-cms/cms/models/placeholdermodel.py", line 577, in copy_plugins
    root_plugin=root_plugin,
  File "/Users/aiky30/Projects/aiky30-github/django-cms/cms/utils/plugins.py", line 213, in copy_plugins_to_placeholder
    new_plugin = CMSPlugin.add_root(instance=new_plugin)
  File "/Users/aiky30/Projects/aiky30-github/django-cms/venv/lib/python3.7/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/Users/aiky30/Projects/aiky30-github/django-cms/venv/lib/python3.7/site-packages/treebeard/mp_tree.py", line 326, in process
    raise NodeAlreadySaved("Attempted to add a tree node that is "\
treebeard.exceptions.NodeAlreadySaved: Attempted to add a tree node that is already in the database
```

The code causing the error in the test
https://github.com/django-cms/django-cms/blob/0e557768af9208f54bea5abe5bb7e629bae2ab88/cms/utils/plugins.py#L213

Also some images showing the state of the model when trying to create a root node:
<img width="1792" alt="Screenshot 2021-02-18 at 11 37 30" src="https://user-images.githubusercontent.com/12543977/108358237-61abd500-71e6-11eb-9abd-a7467f11531c.png">
<img width="1792" alt="Screenshot 2021-02-18 at 11 37 40" src="https://user-images.githubusercontent.com/12543977/108358251-67091f80-71e6-11eb-8d38-370374fa1a47.png">

**Comment by Aiky30** [comment]
This does appear to follow guidelines from Django regarding copying a model: https://docs.djangoproject.com/en/3.2/topics/db/queries/#copying-model-instances

I suspect the deep copy is to ensure that any plugin children are copied which is a fundamental implementation in the CMS: https://www.programiz.com/python-programming/shallow-deep-copy

**Comment by tabo** [comment]
@Aiky30 Thanks for the report. I filed #212 to discuss ways to prevent this kind of problems in the future and would appreciate your input there.

On this ticket, I'm wrapping my head around it. You mention django-cms checks that `_state.created is False` but I can't find that in the source code. If this is the case, _state.created is undocumented as per https://docs.djangoproject.com/en/3.2/ref/models/instances/#state unless you meant `_state.adding` ?

Also, from reading the Django docs you sent about cloning, in https://docs.djangoproject.com/en/3.1/topics/db/queries/#copying-model-instances , Django forgets about `_state.adding`. If I'm understanding this correctly, this is a bug in Django (docs). Because of https://docs.djangoproject.com/en/3.1/ref/models/instances/#state there needs to be a `_state.created = True` during cloning.

**Comment by Aiky30** [comment]
@tabo You are indeed correct that I meant _state.adding and _state.created is a typo. The images that I shared show _state.adding.

That is a big oversight in the Django docs that does need to be patched. 

I will contribute my comments to the release issue.

**Comment by Aiky30** [comment]
Sadly django-cms also relied on the depth PositiveInteger field being empty, I can't see a simple solution to this as looking for 1 doesn't mean the same thing a when it was empty before. :-(

https://github.com/django-cms/django-cms/blob/97654bd78db56b6f4ddc3ce7395f39efb6ba1e80/cms/models/pluginmodel.py#L257

**Comment by Aiky30** [comment]
This change should be reversed going by Django's docs:
"class PositiveIntegerField(**options)
Like an IntegerField, but must be either positive or zero (0). Values from 0 to 2147483647 are safe in all databases supported by Django. The value 0 is accepted for backward compatibility reasons."

https://docs.djangoproject.com/en/3.2/ref/models/fields/#positiveintegerfield

**Comment by tabo** [comment]
@Aiky30 We're discussing reverting the default depth field in #211 because it is unnecessary.

**Comment by johanneswilm** [comment]
@Aiky30 @tabo @gasman Yeah I also found in the documentation that this shouldn't be needed. Logical question for all of you: why can one find so many instances of `PositiveIntegerField(null=True)` if null is accepted anyway? Like here [1] or here [2]. Was there a time when the PositiveIntegerField did not work as described in the documentation? Maybe in one of the database backends? Could that explain why it was added?

[1] https://github.com/django-cms/django-cms/blob/4d75b926fda163e476d3af3a7a534276429d66d6/cms/migrations/0018_create_pagenode.py#L93

[2] https://github.com/django/django/blob/a948d9df394aafded78d72b1daa785a0abfeab48/tests/admin_filters/models.py#L11

**Comment by johanneswilm** [comment]
We could change to using a double check. That way it will work as it did earlier when using regular pk fields and only use the new logic in other cases. That would mean changing a few instances of `if not newobj._state.adding` to `if newobj.pk and not newobj._state.adding`.

This would then work for any project using the (likely buggy) description of how to copy an object that is currently in the django documentation.

**Comment by tabo** [comment]
@johanneswilm I don't think that is necessary, it will potentially cause more corner case errors with users cloning objects. This is a bug in Django's docs, for a feature that is officially supported by them. We're following their API. I think the path forward for us is to add a big caveat in the docs for users that find the need to clone their objects.

**Comment by johanneswilm** [comment]
@tabo My PR on the django documentation has been accepted. So yes, I agree, we are doing this right in 4.5, but may have to point others to the updated documentation if they used the previous instructions.

**Comment by tabo** [comment]
@johanneswilm That's great news! If it's merged, let's link to the updated recommendations in a caveats section in the docs.

**Comment by johanneswilm** [comment]
@tabo You can see it here: https://docs.djangoproject.com/en/3.2/topics/db/queries/#copying-model-instances
