### ISSUE TITLE
sqlite / postgres different treatment for dump_bulk?

### ISSUE THREAD

**Issue by justmars** [django-treebeard/django-treebeard#219]
Environment:
1. Django: 3.1.7
2. Python 3.9.1
3. Treebeard: 4.5.1

Using *sqlite* as a test case I load key values from a yaml file like so:
```python
results: list[tuple] = self.get_data_from_file(f"{f}.yaml")
first_topic_name: str = results[0][0]
root = Topic.add_root(name=first_topic_name)
for parent, child in results:
    p = create_parent_node(parent, root.path)
    p.add_child(name=child)
```
This creates objects in the database and when performing `dump_bulk`, correctly results in the "data-children" combo.

Applying the same mechanism in *postgresql* (I copied the same django app), I'm able to create the objects in the database just fine... but when performing `dump_bulk`, I get a KeyError:
```
----> 1 Topic.dump_bulk(Topic.get_root_nodes()[0])
~/Code/lawdb/.venv/lib/python3.9/site-packages/treebeard/mp_tree.py in dump_bulk(cls, parent, keep_ids)
    653             else:
    654                 parentpath = cls._get_basepath(path, depth - 1)
--> 655                 parentobj = lnk[parentpath]
    656                 if 'children' not in parentobj:
    657                     parentobj['children'] = []
KeyError: '000100020004'
 ```
 
Have no idea what's causing the discrepancy. Tried searching but the closest related problem I could find dealt with [deleted items and broken trees](https://github.com/django-treebeard/django-treebeard/issues/69#issuecomment-355347616). But no deletions were made in the scenario above.

**Comment by solarissmoke** [comment]
Would you be able to provide sample data that triggers this error?

**Comment by mvaled** [comment]
@solarissmoke I stumbled with this issue today and open a PR for it.  It might happen that model's `Meta` have an ordering that is not compatible with the top-down structure of the algorithm, or simply that the DB would return the nodes in an arbitrary order and not necessarily top-down.
