### ISSUE TITLE
When new version with Django 3.2 support could be released?

### ISSUE THREAD

**Issue by idegtiarov** [django-treebeard/django-treebeard#230]
We are looking forward to using `django-treebeard` with Django 3.2

Required PR is already merged into master branch #224.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by solarissmoke** [comment]
@idegtiarov the currently released version of Treebeard already works with Django 3.2. #224 was merely adding it to the test matrix. If you have run into issues with it on Django 3.2, please create an issue with the specific problems encountered. Thanks.
