### ISSUE TITLE
How to change parent node

### ISSUE THREAD

**Issue by JesusGR4** [django-treebeard/django-treebeard#238]
Hello!
I'm developing a category tree and I have the following question:
We have category1, which is child of category 2. Category 1 has 2 children, category3 and category4. Now, Marketing ask us to change the parent of category1 to category5, which is a new one created by them today. Hoy can I change this parent and maintaining the children of category1? 
Thanks!!!!

**Comment by solarissmoke** [comment]
Please refer to the documentation: https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.move
