### ISSUE TITLE
How exactly to run and determine optimal value for Materialized Path's alphabet? (TREEBEARD_TEST_ALPHABET)

### ISSUE THREAD

**Issue by wanglophile** [django-treebeard/django-treebeard#240]
[The documentation](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node.alphabet) reads:

> In case you know what you are doing, there is a test that is disabled by default that can tell you the optimal default alphabet in your enviroment. To run the test you must enable the TREEBEARD_TEST_ALPHABET enviroment variable:
> $ TREEBEARD_TEST_ALPHABET=1 py.test -k test_alphabet

I've asked around a few places and nobody can tell me how to actually run the test and determine the optimal value for alphabet.

**Comment by wanglophile** [comment]
As an aside, I'm using PostgreSQL so I tried setting alphabet to "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" - but as soon as I create a 36th root node, I get this error:
`django.db.utils.IntegrityError: duplicate key value violates unique constraint "appname_modelname_path_key"
DETAIL:  Key (path)=(000a) already exists.`

**Comment by guy881** [comment]
I get the same error when adding 36th node. I ended up using the default alphabet because of this.

**Comment by solarissmoke** [comment]
> I've asked around a few places and nobody can tell me how to actually run the test and determine the optimal value for alphabet.

The documentation describes what you need to do to run the test? 

```
TREEBEARD_TEST_ALPHABET=1 py.test -k test_alphabet
```

That will run the test, and report the optimal alphabet for your current setup. What happened when you tried that? 

I'm closing this for now on the basis that it works as expected - feel free to leave a comment if you can't get it to run.
