### ISSUE TITLE
No easy way to migrate from a parent foreign key to an MP_Node

### ISSUE THREAD

**Issue by kkavod** [django-treebeard/django-treebeard#244]
I am trying to move an existing project with tons of existing data that relies on parent foreign key concept to django-treebeard.
Creating a data migration that would support moving the old models to MP_Node derived models seems to be challenging.
I read @tabo's comment about using load_bulk() and dump_bulk() but that's not a straight forward solution either.
Are there any plans for implementing a way for such a migration?
Thank you!

**Comment by solarissmoke** [comment]
`load_bulk` is the correct way to do this - I think it's infeasible for Treebeard to provide a migration that is generic enough to support all the different types of foreign key structures that you might be migrating from. What makes you say that `load_bulk` is not a straightforward solution? `load_bulk` has a fairly simple API that allows you to pass it an entire tree in a simple structure. Were there particular issues you ran into with creating this structure?
