### ISSUE TITLE
Is python 3.10 supported?

### ISSUE THREAD

**Issue by caarmen** [django-treebeard/django-treebeard#249]
I see that some popular projects using django-treebeard support python 3.10:

* [Wagtail](https://github.com/wagtail/wagtail)
* [django-cms](https://github.com/django-cms/django-cms)

Does this mean that django-treebeard supports python 3.10?  If so, would it be possible to update the readme with this information?

Many thanks!

**Comment by ford-carta** [comment]
Also wondering if I can use this for Django 4.0 and python 3.10

**Comment by Afani97** [comment]
Any update as to support for either Django 4.0 or greater and python 3.10?

**Comment by solarissmoke** [comment]
Django 4.0, 4.1 are both supported, as is Python 3.10 and 3.11 . I've just updated the test matrix, and will try to get a new release out over the holidays so that pypi reflects this support as well.
