### ISSUE TITLE
Content Security Policy: nonce

### ISSUE THREAD

**Issue by snowman2** [django-treebeard/django-treebeard#250]
https://django-csp.readthedocs.io/en/latest/nonce.html

Any issues adding this to `<script>` tags with inline JS?
```html
<script nonce="{{nonce}}">
```
It shouldn't break anything if the `nonce` attribute is not there.

**Comment by solarissmoke** [comment]
Treebeard doesn't depend on django-csp, so we wouldn't be able to add a nonce unless we add it as a dependency. There are [plans to merge the django-csp functionality into Django](https://code.djangoproject.com/ticket/15727), at which point Treebeard will be able to leverage that and add a CSP nonce to its scripts.
