### ISSUE TITLE
Search removed when moving back from admin page

### ISSUE THREAD

**Issue by tanveersultan53** [django-treebeard/django-treebeard#251]
On the admin page, whenever a user searches for a any model , views its details and then goes back to the admin page via the breadcrumb at the top, the search disappears.
create admin page list result by using django-treebeard

**Comment by solarissmoke** [comment]
I don't think this has anything to do with Treebeard. The admin page doesn't include a search form - it's only visible on the side panel when you are viewing the admin page for a particular model.
