### ISSUE TITLE
jquery-ui vulnerabilities

### ISSUE THREAD

**Issue by CN91** [django-treebeard/django-treebeard#253]
https://www.tenable.com/plugins/was/113042
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-31126/Jquery-Jquery-Ui.html

All versions below 1.13 are affected (!!!) and you are using 1.8.5 ;)

It would be great if you could update and negate these vulnerabilities! 

XSS and Exec Code XSS possibilities ;)

**Comment by solarissmoke** [comment]
Thanks for this. We aren't affected by those vulnerabilities (Treebeard only uses one specific utility in jquery UI, not the widgets affected by those vulnerabilities). In any case, I've opened a PR to drop jQuery UI completely.

**Comment by CN91** [comment]
Hi!

I didn't expect a reaction anymore after this amount of time. Good to see that you also removed the entire dependency. 

When do you expect this to be released?

**Comment by jrief** [comment]
@solarissmoke shall I release a new version?

**Comment by solarissmoke** [comment]
@jrief not yet - I'd like to get these reviewed/merged before we cut a release. Do you have any time to review?

- https://github.com/django-treebeard/django-treebeard/pull/261
- https://github.com/django-treebeard/django-treebeard/pull/263

**Comment by solarissmoke** [comment]
@jrief I've cut a new release today (4.6.0).

**Comment by CN91** [comment]
Thanks :D
