### ISSUE TITLE
JOIN (or fetching) with children for MP_Node models

### ISSUE THREAD

**Issue by elgin9507** [django-treebeard/django-treebeard#254]
I need to select all related children of given queryset. Solution I use:

        for q in list(queryset):
            queryset |= q.get_children()

As you can guess, this is not an optimal solution. Is there any other more optimal solution?

**Comment by solarissmoke** [comment]
MP_Node's data structure is not really optimised for this sort of query - there is no foreign key relationship between parents and children, only a path, which makes it easy to efficiently query for all the descendants of a node for example. 

If you do this sort of thing often then you may want to consider adding additional fields to your model to facilitate such queries - e.g., a foreign key that you can use to prefetch all the children of nodes in a queryset. You can find one example of this approach [here](https://stackoverflow.com/questions/36568588/how-to-prefetch-descendants-with-django-treebeards-mp-node).
