### ISSUE TITLE
django.db.utils.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by andychoi** [django-treebeard/django-treebeard#266]
With Django 4.1.x, django-treebeard have issues
When calling **update_or_create** method, I have **django.db.utils.IntegrityError: UNIQUE constraint failed** error

Please advise

**Comment by solarissmoke** [comment]
@andychoi please can you provide a bit more detail for each of these issues:

1. Some sample code to reproduce the issue, or a failing test case.
2. Again, steps to reproduce the issue. The Django admin does not use Bootstrap 5, so there is likely some customisation you have applied which is the cause of the issue.

**Comment by andychoi** [comment]
This is how I fixed by adding custom method; mimicking django's default Query method.

```
class Dept(MP_Node):

   # fields...

    """ overide django due to MP_Node
        defaults = {'key':value, ...}
    """ 
    def update_or_create(parent=None, defaults=None, **kwargs):
        created = False
        try:
            obj = Dept.objects.get(name=kwargs['name'])
            for key, value in defaults.items():
                setattr(obj, key, value)
            obj.save()
        except Dept.DoesNotExist: 
            new_values = {'name':kwargs['name'] }
            new_values.update(defaults)
            if parent:
                if isinstance(Dept):
                    obj = parent.add_child(**new_values)
                else:
                    raise Exception("parent is not Dept instance")
            else:
                obj = Dept.add_root(**new_values)
            created = True
        return obj, created
```

In templates/admin/base_site.html
```
{% block extrastyle %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> 
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>  
{% endblock %}
{% block bodyheader %}

    {% if user.is_authenticated %} 
    <header class="site-header">
        <div class="container fixed-top">
            {% include "includes/nav-admin.html" %}
        </div>
    </header>
    {% endif %}

    <div class="content bg-white container-fluid my-admin-content">
        <div class="row">
{% endblock bodyheader %}
```

**Comment by andychoi** [comment]
Let me know if you also want nav-admin.html contents. It is simple bootstrap 5 navbar.

**Comment by andychoi** [comment]
> @andychoi please can you provide a bit more detail for each of these issues:
> 
> 1. Some sample code to reproduce the issue, or a failing test case.
> 2. Again, steps to reproduce the issue. The Django admin does not use Bootstrap 5, so there is likely some customisation you have applied which is the cause of the issue.

Failing case is when I call Query update_or_create method like
``` Dept.objects.update_or_create( name='new dept', defaults = { 'other_field: 'value', ... } )```

**Comment by andychoi** [comment]
Below codes are Django management/commands/fix_tree.py
I got error in **bulk_update**. Please help.

**django.db.utils.IntegrityError: UNIQUE constraint failed: common_dept.path**

```
import logging
from django.core.management.base import BaseCommand, CommandError
from django.apps import apps
from treebeard.mp_tree import MP_Node

class Command(BaseCommand):
    help = 'Fix path in Tree model (Treebeard)'

    """ not working... hmm.."""
    def handle(self, *args, **options):
        self.update_paths_nodemodel("common", "Dept")


    """ based on node model
    """
    def update_paths_nodemodel(self, app, mdl):
        # update if needed
        steplen = MP_Node.steplen
        alphabet = MP_Node.alphabet
        node_order_by = ["name"]

        Node = apps.get_model(app, mdl)
        nodes = Node.objects.all().order_by(*node_order_by)
        for i, node in enumerate(nodes, 1):
            # for default values, this resolves to: "{:04d}".format(i)
            node.path = f"{{:{alphabet[0]}{steplen}d}}".format(i)
        if nodes:
            Node.objects.bulk_update(nodes, ["path"])
```

**Comment by solarissmoke** [comment]
As regards the integrity error, it's not entirely clear to me what you are trying to do, but you are running into integrity errors simply because you have existing objects in the database with the same path. A few things you can consider:

- If your tree is corrupted then use [fix_tree](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node.fix_tree) instead of implementing your own logic for this.
- If you do need to update all the paths in bulk, you will have to temporarily turn off uniqueness constraints on the path. See [this comment](https://github.com/django-treebeard/django-treebeard/issues/125#issuecomment-645684927) for an example of how this is done in a data migration.

As regards the Django admin, I'm afraid it's still not clear what this has to do with Treebeard. Treebeard relies on the default Django admin templates and styles - if something isn't working when you add Bootstrap 5 to the admin, it's likely something you have to fix in your project.
