### ISSUE TITLE
The ordering of nodes in the Django Admin Panel is not being displayed properly.

### ISSUE THREAD

**Issue by sahilrl** [django-treebeard/django-treebeard#271]
I was expecting that after creating a child node, it will rearrange itself to be displayed just after the parent Node.

For example, here the Node D left the sequence and is displayed just after the parent Node A
```
Node A
         Node D   ...( D is child of A )
Node B
Node C
Node E
```
But rather, it happens something like this.
```
Node A
Node B
Node C
         Node D   ...( D is child of A )
Node E
```
Is it intentional or customizable?

**Comment by solarissmoke** [comment]
We will need a bit more detail to be able to help - i.e., the specific steps to reproduce, and your concrete model definition. It works fine by default so it's likely you have added custom model ordering to conflict with Treebeard's.

**Comment by sahilrl** [comment]
Oh yes, there was custom ordering set. It was mentioned in the documentation. I somehow missed it. Thankyou)
