### ISSUE TITLE
how to handle bulk create

### ISSUE THREAD

**Issue by ansocha** [django-treebeard/django-treebeard#274]
Hi, 

I just ran across django-treebeard while working with django-mptt.

One particular issue and setback for me with django-mptt is with using bulk_create.

How does django-treebeard handle bulk_creates without necessarily rebuilding the entire tree which can be a very expensive operation with large number of records?

Thank you

**Comment by solarissmoke** [comment]
Treebeard provides a [`load_bulk`](https://django-treebeard.readthedocs.io/en/latest/api.html?highlight=load_bulk#treebeard.models.Node.load_bulk) helper to make this easier.
