### ISSUE TITLE
Unique together?

### ISSUE THREAD

**Issue by DmitiyPi** [django-treebeard/django-treebeard#275]
Hello.
I'm using an example from the documentation.
I add a value
>>> get(node.pk).add_sibling(name='Hard Drives')
<Category: Category: Hard Drives>

and then add a value again
 >>> get(node.pk).add_sibling(name='Hard Drives')
<Category: Category: Hard Drives>

I get a duplicate. How to avoid this?
unique_together = [['path', 'name']] does not work.

**Comment by solarissmoke** [comment]
`add_sibling` will create a different `path` value to the first entry (since it is adding a sibling to the first object), which is why the unique together constraint doesn't kick in. You will need to implement your own validation logic to ensure children with identical names aren't created.
