### ISSUE TITLE
publish 4.7 release to pypi?

### ISSUE THREAD

**Issue by shapiromatron** [django-treebeard/django-treebeard#279]
I saw 4.7 was released on [github](https://github.com/django-treebeard/django-treebeard/releases/tag/4.7), but it doesn't yet appear on [pypi](https://pypi.org/project/django-treebeard/). Could the release be uploaded to pypi as well?

Thank you for this wonderful package!

**Comment by solarissmoke** [comment]
Hmm looks like @jrief forgot to do that - I'll do it at some point soon. There are no functional changes in this release though, it's just changing which versions of Django the package declares support for.

**Comment by jrief** [comment]
@tabo I just added a file `publish.yml` to GitHub actions. Unfortunately only the owner of the PyPI repository (YOU) can add the secret token, which is required to add the publishing hook in GitHub.

So please create a token on PyPI https://pypi.org/manage/project/django-treebeard/settings/ and create a new repository secret at https://github.com/django-treebeard/django-treebeard/settings/secrets/actions.

The name of the token is `PYPI_API_TOKEN_TREEBEARD` but you can choose any other name, if you like.

This will allow us maintainers to publish new versions directly from GitHub.

**Comment by tabo** [comment]
Token added!

**Comment by jrief** [comment]
@tabo unfortunately your token has a typo, it's named `PYPI_API_TOKEN_TEEBEARD` instead of `PYPI_API_TOKEN_TREEBEARD`. If you made the same typo on PyPI, I'll just update the `publish.yml` and change it there. However, I have no access to PyPI's package settings to check this.

**Comment by tabo** [comment]
@jrief 

Re-uploaded the secret, hopefully without the typo.

I also made you Owner in treebeard's PyPi, I thought I had done that already. 

Cheers!

**Comment by jrief** [comment]
Thanks @tabo for updating the secret.

Version 4.7 is now the first one published on PyPI via GH actions rather than uploading using a local twine.

**Comment by shapiromatron** [comment]
Thanks everyone!
