### ISSUE TITLE
Please release patch for Content-Security-Policy errors because of inline script

### ISSUE THREAD

**Issue by fblampe** [django-treebeard/django-treebeard#295]
A [recent commit](https://github.com/django-treebeard/django-treebeard/commit/4c44417d76c59ed08f848748d66286278e55e063) fixed an issue with an inline script that causes errors when an app that uses treebeard is served with reasonable content security policies.

Would it be possible to please get a release including that commit anytime soon so apps don't have to compromise their CSP settings as an insecure workaround?

**Comment by DesignsToGrow** [comment]
I ran into the same issue and would love to see this in a release.

**Comment by jrief** [comment]
Release 4.7.1 is available from PyPI.

**Comment by fblampe** [comment]
Great, thank you!Am 31.01.2024 17:36 schrieb Jacob Rief ***@***.***>:
Release 4.7.1 is available from PyPI.
