### ISSUE TITLE
Bring test infrastructure back in shape

### ISSUE THREAD

**Issue by yakky** [django-treebeard/django-treebeard#39]
Maybe using Travis + AppVeyor (for windows testing)?

**Comment by jrief** [comment]
On DuTH, @maikhoepfel declared intention to do this. Is this still the case?

**Comment by maikhoepfel** [comment]
Yes!

**Comment by maikhoepfel** [comment]
A decent test infrastructure is achieved by https://github.com/django-treebeard/django-treebeard/pull/49. I think Windows support can safely be done in a separate PR.

**Comment by yakky** [comment]
\o/
