### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by JoshAddington** [django-treebeard/django-treebeard#50]
Now that treebeard has been migrated to the django-treebeard org and has more contributors, what is work is needed in order to get the next release released? I know a number of us are waiting for the Django 1.10 compatibility to be pushed to pypi.

**Comment by jrief** [comment]
As soon as all the running tests are visible on Travis-CI, I'll push version 4.0.2 onto PyPI.
However, PR #48 is not merged yet.

**Comment by elpescado** [comment]
Hi, I'm one of those waiting for Django 1.10 support.

**Comment by maikhoepfel** [comment]
Just as a note, if we merge https://github.com/django-treebeard/django-treebeard/pull/49 before the release, we should bump the version number to 4.1 as it removes Django 1.7 support. 

Either way, a release in the following days seems likely :)

**Comment by jrief** [comment]
But with Django-1.7, Python 2.7 or 3.4 all tests passed. So this shouldn't be a major issue.

**Comment by jrief** [comment]
Ah, I see. Tests for Django-1.7 have been removed completely. Any reason for this?

**Comment by maikhoepfel** [comment]
Django 1.7 is not officially supported any more. Basically. I think
supporting the 4 officially supported Django versions is more than enough,
and users should be migrating towards Django versions that get security
updates anyway.

**Comment by jrief** [comment]
django-treebeard with support for Django-1.10 has just been released on PyPI.
