### ISSUE TITLE
node.move(target) does not set the parent_id

### ISSUE THREAD

**Issue by jrief** [django-treebeard/django-treebeard#52]
Could someone please confirm this assumption.

We have ``node1`` in the tree, which is a child of ``node2``.
Somewhere else in the tree, there is a ``node3``.

If I invoke ``node1.move(node3, pos='last-child')`` I would assume that  afterwards ``node1.parent_id == node3.id``, but that's not the case, ``node1.parent`` still points onto ``node2``.

Did I miss something in the documentation, is this a misconception from my part, or just a bug?

**Comment by Arany** [comment]
Can you check, whether `node3` is child of `node2`? If so, this is correct behavior according to the documentation, as you left out the `pos` parameter, that defaults to `last-sibling`.

**Comment by jrief** [comment]
Updated statement, but with the same result.

**Comment by luissalgadofreire** [comment]
Hi. Is there any update on this issue? I'm experiencing the same problem. I'm simply not able to move a node to a target using the move() method. In my case, I have a sorted ``MP_Node`` and am trying to move node ``s2`` to a new parent node ``d1`` using ``s2.move(d1, 'sorted-child')``.

My model inherits from ``MP_Node``, i'm using ``objects = MP_NodeManager()`` as the default manager and am sorting with ``node_order_by = ['name']``.

Am I doing something wrong? It works in the admin using ``TreeAdmin`` so can't understand why it's not working when using it directly.

**Comment by xPapp** [comment]
+1

**Comment by stickperson** [comment]
@jrief  I don't believe this is an issue any longer. As far as I can tell, `parent_id` no longer exists. Instead you can use `node1.get_root()`. In your example, after running `node1.move(node3, pos='last-child')`, `node1.get_root()` still returned `node2`. However, `node1.refresh_from_db()` seemed to work. I would assume this happens because `node1`'s `path` changes and the instance has to reflect that change.

**Comment by tabo** [comment]
This is explained in the documentation: https://django-treebeard.readthedocs.io/en/latest/caveats.html#raw-queries

Move calls in NS and MP trees are heavily reliant on raw queries, so if the object is going to be used after calling it, it would be safest to reload from the database.
