### ISSUE TITLE
Issue moving existing MP_Node to root node with no children.

### ISSUE THREAD

**Issue by zbyte64** [django-treebeard/django-treebeard#59]
An existing leaf node is moved to a newly created root node. 

```
  File "/code/apps/datasets/models.py", line 77, in set_sub_organization_of
    self.move(parent, 'sorted-child')
  File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 1046, in move
    return MP_MoveHandler(self, target, pos).process()
  File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 444, in process
    if self.target.is_descendant_of(self.node):
AttributeError: 'NoneType' object has no attribute 'is_descendant_of'
```

At some point target is changed from parent to sibling, but there are no siblings. This happens inside: `MP_MoveHandler.update_move_to_child_vars` .

**Comment by zbyte64** [comment]
Also this issue happens when I try to move nodes in the admin but only to one particular empty root node. Other empty root nodes are handled okay.

**Comment by jrief** [comment]
are you sure, that the tree is in consistent state?
Did you invoke the [find_problems()](http://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.find_problems) method?

**Comment by zbyte64** [comment]
That worked, guess it was bad state, sorry.

**Comment by mihalikv** [comment]
Same issue here. I want to move child from one root to another. New root is without children and same `AttributeError` is raised and `find_problems` result in `([], [], [], [], [])` and i also tried `fix_tree`.
