### ISSUE TITLE
Documentation should include Python 3

### ISSUE THREAD

**Issue by dcolumbus** [django-treebeard/django-treebeard#60]
I'm new to this library and Django overall, but it would be very helpful if you could include Python 3 instructions within your documentation.

I ran into the issue where the Admin interface was displaying my Model as "Category object" instead of the name of the object... this was because the documentation uses Python 2 syntax `__unicode__` instead of guiding Python 3 users to replace that with `__str__`

**Comment by jrief** [comment]
Thanks for reporting.

This is a bug, which can be easily fixed by using the ``@python_2_unicode_compatible`` decorator on top of each class implementing ``__unicode__`` and replacing the latter by ``__str__``.

Do you want to create a pull request?

**Comment by jrief** [comment]
please review my doc fix

**Comment by dcolumbus** [comment]
Yes, this looks good. Or you could simple do what the official Django docs do:

`def __str__(self):     # __unicode__ on Python 2`
