### ISSUE TITLE
Node.delete doesn't support 'using' kwarg

### ISSUE THREAD

**Issue by skirsdeda** [django-treebeard/django-treebeard#61]
Django model instance ```delete``` method supports ```using``` kwarg since at least Django 1.7. 
treebeard's ```Node.delete``` should support it as well, but then ```delete``` method on node querysets might have to be fixed as well.

**Comment by mireq** [comment]
Some django applications (eg parler) always send `using` argument. I use this monkey patch to fix error `TypeError: delete() takes 1 positional argument but 2 were given`:

```python
def monkey_patch_treebeard_delete():
    from treebeard.models import Node

    def delete(self, using=None):
        self.__class__.objects.using(using).filter(pk=self.pk).delete()

    Node.delete = delete
```
