### ISSUE TITLE
django 1.10 compatibility - future template tag library removed

### ISSUE THREAD

**Issue by racitup** [django-treebeard/django-treebeard#64]
I have an scss compiler that scans all templates. It gave this error:

> Invalid template ../.pyenv/versions/3.5.2/lib/python3.5/site-packages/treebeard/templates/admin/tree_list_results.html: 'future' is not a registered tag library. Must be one of:
> admin_list
> admin_modify...

Due to the following in `tree_list_results.html`
`{% load cycle from future  %}`

[Same issue here](https://github.com/s-block/django-nested-inline/issues/65)

**Comment by nikolas** [comment]
Looks like this was addressed in version 4.1.1? https://github.com/django-treebeard/django-treebeard/blob/master/CHANGES#L4

**Comment by racitup** [comment]
[This commit](https://github.com/django-treebeard/django-treebeard/commit/eee47216fec59475211c4c699a1776e3596b7364#diff-37c5379a6d58b03c30a54722852123e4) fixed it..
