### ISSUE TITLE
Cannot delete broken tree.

### ISSUE THREAD

**Issue by zbyte64** [django-treebeard/django-treebeard#69]
Sometimes one cannot succeed in running `fix_tree(destructive=True)` and resorts instead to using `objects.all().delete()` to start fresh. But it seems that is not always possible if the tree is broken:

```
>>> Concept.objects.all().delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 112, in delete
    parents[parentpath] = node.get_parent(True)
  File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 1072, in get_parent
    self.__class__).objects.get(path=parentpath)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
apps.focus.models.DoesNotExist: Concept matching query does not exist.
```

There should be a guaranteed programmatic way to reset the table state even if the tree paths are broken.

**Comment by zbyte64** [comment]
Current hack around incase anyone else needs to do this:

```
f = Concept.objects.all()
from django.db.models import QuerySet
QuerySet.delete(f)
```

**Comment by jrief** [comment]
Please always add the Django version you are using.

**Comment by zbyte64** [comment]
django==1.10.6
django-treebeard==4.1.2

**Comment by jhrr** [comment]
Had the same issue which I *could* fix with the above `QuerySet` hack but also managed to cause a `KeyError` when attempting `fix_tree(destructive=True)`. Here's the traceback:

```
In [8]: ConditionGroup.fix_tree(destructive=True)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-67a4ab5ed8ee> in <module>()
----> 1 ConditionGroup.fix_tree(destructive=True)

~/.virtualenvs/fathom/lib/python3.6/site-packages/treebeard/mp_tree.py in fix_tree(cls, destructive)
    769
    770         if destructive:
--> 771             dump = cls.dump_bulk(None, True)
    772             cls.objects.all().delete()
    773             cls.load_bulk(dump, None, True)

~/.virtualenvs/fathom/lib/python3.6/site-packages/treebeard/mp_tree.py in dump_bulk(cls, parent, keep_ids)
    660             else:
    661                 parentpath = cls._get_basepath(path, depth - 1)
--> 662                 parentobj = lnk[parentpath]
    663                 if 'children' not in parentobj:
    664                     parentobj['children'] = []

KeyError: '0001'
```

Django==1.11.6
django-treebeard==4.2.0

**Comment by mhoonjeon** [comment]
@jhrr hi there did you manage to fix the KeyError? I'm getting the same error when invoking `dump_bulk` method. The funny thing is Category.dump_bulk works the first time, but keyerror is raises after the first try. :(
I'm lost and need help with this 🙏

**Comment by jhrr** [comment]
@mhoonjeon sorry I didn't, I can't quite remember how I worked around it but I never got any further with the `KeyError` than this. Good luck!

**Comment by tabo** [comment]
There is a whole new implementation of `fix_tree(destructive=True)`. Please file another ticket if there are other issues.
