### ISSUE TITLE
missing quote in dismissRelatedLookupPopup

### ISSUE THREAD

**Issue by Air-Mark** [django-treebeard/django-treebeard#72]
There is a missing quote when we use raw_id_fields  in django admin [templatetags/admin_tree.py](https://github.com/django-treebeard/django-treebeard/blob/master/treebeard/templatetags/admin_tree.py#L169)

**Comment by jrief** [comment]
can you please be more specific

**Comment by Air-Mark** [comment]
At the row that I mentioned we take the representation of the string without the first char, as I understand the first char is 'u'. But for the 3d python there is no 'u' char in representation.

**Comment by stefanw** [comment]
@jrief I opened a PR that fixes the faulty behaviour: https://github.com/django-treebeard/django-treebeard/pull/89
