### ISSUE TITLE
IntegrityError using MoveNodeForm with predefined primary key

### ISSUE THREAD

**Issue by likhvar** [django-treebeard/django-treebeard#75]
MoveNodeForm fails with IntegrityError if primary key was pregenerated for new instance. For example:

```
def get_instance_serial():
    return SomeModel.objects.all().order_by('id').last().pk

class SomeModel(models.Model):
    id = models.PositiveIntegerField(
        primary_key=True,
        default=get_instance_serial,
        editable=False)    
```
results in:
`django.db.utils.IntegrityError: null value in column "lft" violates not-null constraint`

[This check](https://github.com/django-treebeard/django-treebeard/blob/master/treebeard/forms.py#L134) should probably include such a case.

**Comment by solarissmoke** [comment]
I believe this was fixed in #245 . Please feel free to reopen if there's still an issue in version 4.6.0 of Treebeard.
