### ISSUE TITLE
4.1.2 version PIP package is not updated.

### ISSUE THREAD

**Issue by pincoin** [django-treebeard/django-treebeard#85]
Hello,

I just installed the latest version 4.1.2 of your nice package using PIP.

`pip install django-treebeard`

After that, I ran the django test server. I encountered the following error:

```
  File "/Users/mairoo/.pyenv/versions/treebeard/lib/python3.6/site-packages/treebeard/admin.py", line 70, in get_urls
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog'
```

I thought making PR, but it was already merged by https://github.com/django-treebeard/django-treebeard/pull/80

However, PIP package still has the old version of `treebeard/admin.py`.

I found out it works fine when I installed it manually `python setup.py install -f` after cloning.

Please, get it updated. Thank you.

**Comment by jrief** [comment]
Thanks for reminding me. Just released version 4.2.0.
