### ISSUE TITLE
UnboundLocalError raised on treebeard admin

### ISSUE THREAD

**Issue by czpython** [django-treebeard/django-treebeard#97]
When an app's admin inherits from `TreeAdmin`, if the `list_display` attribute contains a field that raises an `ObjectDoesNotExist` error, treebeard will raise the following exception:

```local variable 'row_class' referenced before assignment```

This happens because the `row_class` [attribute](https://github.com/django-treebeard/django-treebeard/blob/4.2.0/treebeard/templatetags/admin_tree.py#L103) is declared inside the else block.

**Comment by jrief** [comment]
Sorry guys, I forgot to push a new version onto PyPI.
Version 4.2.1 ist available right now.

**Comment by czpython** [comment]
Thanks but this is not fixed with 4.2.1
The variable is still on the `else` block.
